
tasks:
  - name: Webserver
    command: >
      gp open style.css;
      gp open index.html;
      python -m http.server 8000

ports:
  - name: Webserver
    port: 8000
    onOpen: open-preview
vscode:
  extensions:
    - esbenp.prettier-vscode